import { sqliteTable, text, integer, real, index } from 'drizzle-orm/sqlite-core'
import { relations } from 'drizzle-orm'
import { parts } from './catalog'
import { stores } from './users'

export const inventory = sqliteTable('inventory', {
  id: text('id').primaryKey(),
  partId: text('part_id').notNull().references(() => parts.id),
  storeId: text('store_id').notNull().references(() => stores.id),
  price: real('price').notNull(),
  currency: text('currency').notNull().default('IQD'),
  quantity: integer('quantity').notNull().default(0),
  condition: text('condition').notNull().default('new'),
  status: text('status').notNull().default('active'),
  installationPrice: real('installation_price'),
  notes: text('notes'),
  notesAr: text('notes_ar'),
  createdAt: integer('created_at', { mode: 'timestamp' }).notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp' }).notNull(),
}, (table) => ({
  storeIdIdx: index('inventory_store_id_idx').on(table.storeId),
  partIdIdx: index('inventory_part_id_idx').on(table.partId),
  priceIdx: index('inventory_price_idx').on(table.price),
  quantityIdx: index('inventory_quantity_idx').on(table.quantity),
}))

export const images = sqliteTable('images', {
  id: text('id').primaryKey(),
  url: text('url').notNull(),
  storageType: text('storage_type').notNull().default('url'),
  inventoryId: text('inventory_id').references(() => inventory.id),
  partId: text('part_id').references(() => parts.id),
  storeId: text('store_id').references(() => stores.id),
  type: text('type').notNull().default('inventory'),
  isAutoGenerated: integer('is_auto_generated', { mode: 'boolean' }).default(false),
  createdAt: integer('created_at', { mode: 'timestamp' }).notNull(),
})

export const inventoryRelations = relations(inventory, ({ one, many }) => ({
  part: one(parts, { fields: [inventory.partId], references: [parts.id] }),
  store: one(stores, { fields: [inventory.storeId], references: [stores.id] }),
  images: many(images),
}))

export const imagesRelations = relations(images, ({ one }) => ({
  inventory: one(inventory, { fields: [images.inventoryId], references: [inventory.id] }),
  part: one(parts, { fields: [images.partId], references: [parts.id] }),
  store: one(stores, { fields: [images.storeId], references: [stores.id] }),
}))
