import { db } from '@/db'
import { images } from '@/db/schema'

interface PhotoSearchResult {
  url: string
  title: string
  width: number
  height: number
}

export async function autoFetchPartPhotos(
  partName: string,
  partNumber: string | null,
  make: string,
  model: string,
  year: string
): Promise<string[]> {
  const searchQuery = buildSearchQuery(partName, partNumber, make, model, year)

  try {
    const results = await searchPartPhotos(searchQuery)
    const highQualityUrls = results
      .filter((r) => r.width >= 400 && r.height >= 400)
      .map((r) => r.url)
      .slice(0, 5)

    return highQualityUrls
  } catch {
    return []
  }
}

function buildSearchQuery(
  partName: string,
  partNumber: string | null,
  make: string,
  model: string,
  year: string
): string {
  const parts = [make, model, year, partName]
  if (partNumber) parts.push(partNumber)
  return parts.filter(Boolean).join(' ')
}

async function searchPartPhotos(query: string): Promise<PhotoSearchResult[]> {
  const encodedQuery = encodeURIComponent(query)
  const url = `https://www.googleapis.com/customsearch/v1?key=${process.env.GOOGLE_SEARCH_API_KEY || ''}&cx=${process.env.GOOGLE_SEARCH_CX || ''}&q=${encodedQuery}&searchType=image&imgSize=large&num=10`

  try {
    const response = await fetch(url)
    if (!response.ok) return []

    const data = await response.json()
    return (data.items || []).map((item: { link: string; title: string; image: { width: number; height: number } }) => ({
      url: item.link,
      title: item.title,
      width: item.image?.width || 0,
      height: item.image?.height || 0,
    }))
  } catch {
    return []
  }
}

export async function saveAutoFetchedPhotos(
  inventoryId: string,
  partId: string,
  storeId: string,
  urls: string[]
): Promise<void> {
  for (const url of urls) {
    await db.insert(images).values({
      id: crypto.randomUUID(),
      url,
      storageType: 'url',
      inventoryId,
      partId,
      storeId,
      type: 'auto_fetched',
      isAutoGenerated: true,
      createdAt: new Date(),
    })
  }
}

export async function saveUserUploadedPhoto(
  inventoryId: string,
  partId: string,
  storeId: string,
  url: string,
  storageType: 'url' | 'upload' = 'url'
): Promise<void> {
  await db.insert(images).values({
    id: crypto.randomUUID(),
    url,
    storageType,
    inventoryId,
    partId,
    storeId,
    type: 'user_uploaded',
    isAutoGenerated: false,
    createdAt: new Date(),
  })
}

export async function getPartPhotos(partId: string): Promise<Array<{ url: string; type: string; isAutoGenerated: boolean }>> {
  return db.select({
    url: images.url,
    type: images.type,
    isAutoGenerated: images.isAutoGenerated,
  })
    .from(images)
    .where((fields) => fields.partId === partId)
}
